### ISSUE TITLE
TK700STi - no connection

### ISSUE THREAD

**Issue by pborsiak** [rrooggiieerr/homeassistant-benqprojector#31]
Hi - after moving to new home, the integration worked once and now drop connection to the projector - tried 2 cables, internal and usb com port, 9600 and 115200 speed - nothing establish the connection. How can I obtain any logs if integration does not enabling itself by successful config?

**Comment by rrooggiieerr** [comment]
You can add/update the following lines to your `configuration.yaml`

```
logger:                                             
  default: info                                     
  logs:                                             
    custom_components.benqprojector: debug         
    benqprojector: debug                           
```

Beware of the indentation!
